version: '3.6'

services:
  logstash:
    image: logstash:7.6.1
    container_name: logstash
    volumes:
    - ./logstash/config:/config
    command: logstash -f /config/logstash.conf
    networks:
    - elk-network
    depends_on:
    - elasticsearch

  elasticsearch:
     image: elasticsearch:7.6.1
     container_name: elasticsearch
     ports:
     - 9200:9200
     - 9300:9300
     environment:
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
     - http.cors.enabled=true
     - http.cors.allow-origin=*
     networks:
     - elk-network
     volumes:
     - ./elasticsearch/es_data:/usr/share/elasticsearch/data/

  kibana:
    image: kibana:7.6.1
    container_name: kibana
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
    - elk-network
    depends_on:
    - elasticsearch

networks:
  elk-network:
   name: elk-global-network