version: '3.6'

services:
  jenkins:
    build: jenkins
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
    - "8080:8080"
    volumes:
    - ./jenkins_home:/var/jenkins_home
    networks:
    - elk-network

networks:
  elk-network:
   name: elk-global-network